name: Focus Daily Extract & Analyze

on:
  schedule:
    - cron: '0 0 * * *' # 매일 00:00 UTC
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Write .env from secrets (root)
        run: |
          echo "GSHEETS_CREDENTIALS_JSON=${{ secrets.GSHEETS_CREDENTIALS_JSON }}" > .env
          echo "GSHEETS_PARENT_FOLDER_ID=${{ secrets.GSHEETS_PARENT_FOLDER_ID }}" >> .env
          echo "GITBOOK_REPO_PATH=${{ secrets.GITBOOK_REPO_PATH }}" >> .env
          chmod 600 .env

      - name: Run extract
        run: go run cmd/focus/main.go extract

      - name: Remove .env (cleanup)
        if: always()
        run: rm -f .env
