name: Go Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: $(go env GOPATH)/bin/golint ./... | tee lint.log 
